name: Polymarket Auto Scanner (Every 15 Minutes)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

concurrency:
  group: polymarket-scan-15min
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests==2.32.3
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          THRESHOLD_HIGH: "0.80"
          THRESHOLD_LOW:  "0.20"
          MIN_LIQ_USD:    "1000"
          MIN_VOL_USD:    "2000"
          MAX_ALERTS:     "10"
        run: python scanner.py
